apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repoURL:  https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.6.0
    helm:
      releaseName: external-dns
      valuesObject:
        clusterName: terraform
        serviceAccount:
          create: true
          name: external-dns-eks
        ignoreDifferences:
        - group: ""
          jsonPointers:
          - /data
          kind: Secret
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: v1=
      kind: Secret
      jsonPointers:
      - /data