apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lattice-gateway
  namespace: argocd
spec:
  project: default
  source:
    chart: aws-gateway-controller-chart
    repoURL: public.ecr.aws/aws-application-networking-k8s/
    targetRevision: 0.0.15
    helm:
      releaseName: aws-gateway-controller-chart
      valuesObject:
        serviceAccount:
          create: true
          name: lattice-eks
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::345796856102:role/lattice-eks-irsa"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true